/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EmailForwarding configures email forwarding for an account.
type EmailForwarding struct {
	// enabled indicates whether forwarding is active.
	Enabled bool `json:"enabled"`

	// addresses is the list of forwarding target email addresses.
	// +optional
	Addresses []string `json:"addresses,omitempty"`

	// keepCopy indicates whether to keep a local copy when forwarding.
	// +kubebuilder:default=true
	// +optional
	KeepCopy bool `json:"keepCopy,omitempty"`
}

// EmailAccountSpec defines the desired state of EmailAccount.
type EmailAccountSpec struct {
	// address is the full email address (e.g. info@example.com).
	// +kubebuilder:validation:MinLength=3
	// +kubebuilder:validation:Pattern=`^[^@]+@[^@]+\.[^@]+$`
	Address string `json:"address"`

	// domain is the email domain (must match an existing EmailDomain).
	// +kubebuilder:validation:MinLength=1
	Domain string `json:"domain"`

	// quotaMB is the mailbox quota in megabytes.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:default=1024
	// +optional
	QuotaMB int32 `json:"quotaMB,omitempty"`

	// forwarding configures email forwarding.
	// +optional
	Forwarding *EmailForwarding `json:"forwarding,omitempty"`

	// passwordHash is the Dovecot-compatible password hash for IMAP/SMTP authentication.
	// Format: {SHA512-CRYPT}$6$... (generated by the panel API, never stored in plaintext)
	// +optional
	PasswordHash string `json:"passwordHash,omitempty"`
}

// EmailAccountStatus defines the observed state of EmailAccount.
type EmailAccountStatus struct {
	// phase is the current lifecycle phase.
	// +kubebuilder:validation:Enum=Pending;Creating;Active;Error;Terminating
	// +optional
	Phase string `json:"phase,omitempty"`

	// maildirPath is the path to the maildir on the User_Volume.
	// Format: mail/{domain}/{account}/
	// +optional
	MaildirPath string `json:"maildirPath,omitempty"`

	// usedMB is the current mailbox usage in megabytes.
	// +optional
	UsedMB int32 `json:"usedMB,omitempty"`

	// conditions represent the current state of the EmailAccount resource.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Address",type=string,JSONPath=`.spec.address`
// +kubebuilder:printcolumn:name="Domain",type=string,JSONPath=`.spec.domain`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Quota",type=integer,JSONPath=`.spec.quotaMB`
// +kubebuilder:printcolumn:name="Used",type=integer,JSONPath=`.status.usedMB`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// EmailAccount is the Schema for the emailaccounts API.
type EmailAccount struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec EmailAccountSpec `json:"spec"`

	// +optional
	Status EmailAccountStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// EmailAccountList contains a list of EmailAccount.
type EmailAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []EmailAccount `json:"items"`
}

func init() {
	SchemeBuilder.Register(&EmailAccount{}, &EmailAccountList{})
}
