apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hosting-panel.fullname" . }}-operator
  namespace: {{ include "hosting-panel.namespace" . }}
  labels:
    {{- include "hosting-panel.operatorLabels" . | nindent 4 }}
