apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hosting-panel.fullname" . }}-panel
  namespace: {{ include "hosting-panel.namespace" . }}
  labels:
    {{- include "hosting-panel.panelLabels" . | nindent 4 }}
